logback:
  path: @project.basedir@/logs

server:
  port: 8080

spring:
  profiles:
    active: production
  application:
    name: 'ms-report-rest'
  jpa:
    open-in-view: false
  datasource:
    jdbc-url: 'jdbc:sqlite:db/app.db'
    driver-class-name: 'org.sqlite.JDBC'
    pool-name: 'CP: APP'
    hibernate:
      dialect: 'org.sqlite.hibernate.dialect.SQLiteDialect'
      show-sql: true
      hbm2ddl:
        auto: 'validate'
  flyway:
    enabled: true
    locations: 'classpath:db/migration'
